server:
  context-path: /seller
  port: 8082

#rpc.manager.url: http://localhost:8081/manager/

logging:
  level:
    com.googlecode.jsonrpc4j: debug

rpc:
  client:
    url: http://localhost:8081/manager
    basePackage: com.imooc.api

spring:
  cache:
    type: hazelcast
  activemq:
    broker-url: tcp://localhost:61616
    packages:
      trust-all: true