spring:
  jackson:
    date-format: yyyy-MM-dd'T'HH:mm:ss.SSS
    time-zone: GMT-4
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/manager?useUnicode=true&characterEncoding=UTF-8&user=root&password=123456";
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
      show-sql: true

server:
  context-path: /manager
  port: 8081